project_id = "snoiymaflwumwlbschau"

[functions.mp-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-trial]
verify_jwt = false

[functions.test-panel]
verify_jwt = false

[functions.test-renewal]
verify_jwt = false
