// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snoiymaflwumwlbschau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub2l5bWFmbHd1bXdsYnNjaGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTIzMDIsImV4cCI6MjA4ODU4ODMwMn0.7zpSqaMEe1AnEAutW3qsno3ZfR68t4CLLE356iRvUr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});